#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
"""
Description:
This script parses a ddsystem.txt file, vndb.org/r?f=fwDDSystem- , generated by github.com/crskycode/DDWSystemTool as input, and returns a spreadsheet.
It also takes a spreadsheet and outputs the hopefully translated contents back into the file.
That spreadsheet is implemented as a Strawberry() class found in the chocolate.py library. A chocolate.Strawberry() is a type of spreadsheet that exists only in memory.

API concept art:
input() processes raw data and converts it to a spreadsheet for further processing.
output() takes data from a processed spreadsheet and inserts it back into the original file.

CLI Usage:
python py3Any2Spreadsheet.py --help
python py3Any2Spreadsheet.py input ddsystemfile.txt ddsystem.parsingTemplate.py
python py3Any2Spreadsheet.py output ddsystemfile.txt ddsystem.parsingTemplate.py --spreadsheet ddsystemfile.txt.xlsx

py3Any2Spreadsheet.py Usage:
import 'resources\templates\txt.ddsystem.parsingTemplate.py' as customParser # But with fancier/messier import syntax.
customParser.input()
customParser.output()

Algorithim (old):
skip empty lines
skip lines that start with ◇
Assert the line starts with ◆
There is always an address/code in between two ◆. Store it as metadata along with the line number.
Ignore lines where the the last character is a number.
Ignore lines where the 2nd to last character is a number.
Ignore lines if the last three characters end in "dat" after converting it to lowercase.
Next, process the string.
If the line starts with \n then ignore the first character.
If the line has a new line character, right next to an "「" then assume the part before that is the speaker's name => "\n「" Do not store the new line character.
If the line ends in _ then ignore it the _ at the end, up to a max of 3 characters/reptitions.

License: See main program.
"""
__version__ = '2024.06.21'


# Set program defaults.
verbose=False
debug=False
consoleEncoding='utf-8'
defaultTextEncoding='utf-8'
defaultOutputColumn=4
metadataDelimiter='_'
defaultTargetEncoding='cp932'

#https://docs.python.org/3.7/library/codecs.html#standard-encodings
inputErrorHandling='strict'
#inputErrorHandling='backslashreplace'
#outputErrorHandling='namereplace'  #This is set dynamically below.


# import stuff
import sys                                                         # Used to sys.exit() in case of an error and to check system version.

import resources.chocolate as chocolate            # Main data structure that wraps openpyxl. This import will fail if not using the syntax in Usage.
# To import directly:
# import sys
# import pathlib
# sys.path.append( str( pathlib.Path('C:/resources/chocolate.py').resolve().parent) )
# import chocolate

import resources.functions as functions              # A helper library that has many functions.
# To import directly:
# import sys
# import pathlib
# sys.path.append( str( pathlib.Path('C:\\resources\\functions.py').resolve().parent) )
# import functions

#Using the 'namereplace' error handler for text encoding requires Python 3.5+, so use an older one if necessary.
sysVersion=int(sys.version_info[1])
if sysVersion >= 5:
    outputErrorHandling='namereplace'
elif sysVersion < 5:
    outputErrorHandling='backslashreplace'    
else:
    sys.exit('Unspecified error.'.encode(consoleEncoding))


"""
Development Guide:
input() is called with the following parameters:
1) fileNameWithPath ; This is rawFile as it was passed to py3AnyText2Spreadsheet at the CLI. It still needs to be opened and read into memory.
2) characterDictionary {} ; This is optional, but if characterDictionary.csv was specified at the CLI, then it will be available here as a Python dictionary. The first row is always reserved for headers and so is ignored when going from characterDictionary.csv->Python dictionary.
3) settings {} ; This is a dictionary that has all of the settings passed to py3AnyText2Spreadsheet at the command line interface and a few extra values.
input() is responsible for returning a completed chocolate.Strawberry() spreadsheet back to py3AnyText2Spreadsheet so it can be written out to disk.

output() is called with the following parameters:
1) fileNameWithPath ; This is rawFile as it was passed to py3AnyText2Spreadsheet at the CLI. It still needs to be opened and read into memory.
2) spreadsheet ; The chocolate.Strawberry() that was created using the input() function and specified at the CLI using the --spreadsheet option will be available here.
3) characterDictionary {} ; This is optional, but if characterDictionary.csv was specified at the CLI, then it will be available here as a Python dictionary. The first row is always reserved for headers and so is ignored when going from characterDictionary.csv->Python dictionary.
4) settings {} ; This is a dictionary that has all of the settings passed to py3AnyText2Spreadsheet at the command line interface and a few extra values.
output() is responsible inserting the translated/completed contents in chocolate.Strawberry() spreadsheet back into fileNameWithPath. Once fileNameWithPath has been updated, it should be sent back as a string, a list of strings, or a chocolate.Strawberry() to be written out to disk.

The settings {} dictionary has all of the parameters passed at the CLI and a few others. These in particular are useful:
settings[ 'fileEncoding' ] - The encoding of rawFile as a string.
settings[ 'parseSettingsDictionary' ] - The parsingTemplate.ini file as a Python dictionary.
settings[ 'outputColumn' ] - The columnToUseForReplacements from the CLI as a string. If a number was specified, it can be converted back using int( settings[ 'outputColumn' ] ) . If one was not specified, then settings[ 'outputColumnIsDefault' ] == True.
settings[ 'translatedRawFileName' ] - The filename and path of the file to use when writing the translated file as output.

Spreadsheet formatting suggestion: https://github.com/gdiaz384/py3TranslateLLM#regarding-the-spreadsheet-formats
The format is based on the format used by VNT, T++, and common sense.
Summary:
Column A should be the extracted rawText.
Column B should be the speaker (if any). If there is none, then leave this column blank. If possible, use the characterDictionary to translate any raw names into their translated forms as this is more convenient to translate + edit.
Column C should be any metadata required to validate and reinsert the contents of Column A and B back into the source text.
As a suggestion for Column C, use the line numbers the input is taken from or the order the input is parsed in, and any other data that is unique to that entry.
Example lists that represent a row for different types of data:
[ 'It is all I can do to hold them off!', None, 15 ]  # .ssa subtitles ; Column C is the entry number. 
[ 'Yes, sir!', 'speaker1', '19_True' ]     # srt subtitles ; Column C is the entry number and if the original entry was split for translation due to multiple speakers appearing in the same entry.
[ '「勉強ねぇ」', None, 'p-009_body p_288' ]  # .ebook ; .ebook ; Column C is the filename_css search tag_entry number, with _ being used as a delimter.
"""


def input( fileNameWithPath, characterDictionary=None, settings={} ):

    if debug == True:
        print( ( 'characterDictionary=' + str(characterDictionary) ).encode(consoleEncoding) )

    # Unpack some variables.
    if 'fileEncoding' in settings:
        fileEncoding=settings['fileEncoding']
    else:
        fileEncoding=defaultTextEncoding

    if 'parseSettingsDictionary' in settings:
        parseSettingsDictionary=settings['parseSettingsDictionary']
    else:
        parseSettingsDictionary=None

    # The input file is actually a .txt file so read it in and convert it into a list of strings.
    with open( fileNameWithPath, 'rt', encoding=fileEncoding, errors=inputErrorHandling ) as myFileHandle:
        inputFileContents = myFileHandle.read().splitlines()

    speakerNameDelimiterList=[ '「', '『', '（' ]
    temporaryList=[]
    for currentLineNumber,line in enumerate(inputFileContents):
        # Skip empty lines.
        if line.strip () == '':
            continue
        line=line.strip()

        # Skip lines that start with ◇.
        if line[0:1]=='◇':
            continue

        # Assert the line starts with ◆.
        assert( line[0:1]=='◆' )

        # These appear to be untranslatable lines because they describe characters, their outfits, expressions and use @ and _ syntaxes.
        # Update: It might be that none of the code lines have \n, and every dialogue line has \n. Is that correct, or are there any counter examples?
#        if line.find( '@' ) != -1:
#            continue

#        if line.find( '_' ) != -1:
#            continue

        # Ignore lines where the the last character is a number.
#        if line[-1:].isdigit() == True:
#            continue

        # Ignore lines where the 2nd to last character is a number.
#        if line[-2:-1].isdigit() == True:
#            continue

        # Ignore lines where the 3rd to last character is a number if the 2nd to last is also an underscore.
#        if ( line[-3:-2].isdigit() == True ) and ( line[-2:-1] == '_' ):
#            continue

        # Ignore lines if the last three characters end in "dat" after converting it to lowercase.
#        if line[-3:].lower() == 'dat':
#            continue

        #Next, process the string.
        speaker = None
        #codeForMetadata = None

        # There is always an address/code in between two ◆. Store it as metadata along with the line number.
        codeForMetadata = line[ 1: line.rfind( '◆' ) ]

        # The address/code has been processed, so remove it now.
        line=line[1:].partition('◆')[2]

        # One off fixes.
#        if ( line.startswith('bg_') ) or ( line =='black' ) or ( line.startswith('ev_') ):
#        if line =='black': # What does this mean?
#            continue

        # if the line starts with \n then ignore the first character and set the line equal the the rest of the line.
        if line[ :2 ] == r'\n':
            line=line[ 2: ].strip() #Added .strip() to ensure no whitespace.
            #speaker=None
        else:
            # if the line has a new line character, right next to an "「" then it might be the part before that is the speaker's name => "\n「" Do not store the new line character.
            #if line.find(r'\n') != -1:
            #index=line.find(r'\n')
            # if the first character after \n is '「'
            #if line[index+2:index+3] in speakerNameDelimiterList:
            speaker=line.partition( r'\n' )[0].strip()
            line=line.partition( r'\n' )[2].strip()

        if ( speaker != None ) and ( characterDictionary != None ):
            if speaker in characterDictionary:
                speaker=characterDictionary[speaker]
            else:
                print( 'Warning: Speaker encountered that was not in character dictionary at line', currentLineNumber)

        # if the line ends in _ then ignore it the _ at the end, up to a max of 3 characters/reptitions.
        # This is probably not necessary since lines with _ at the end are assumed to be code.
#        for i in range(3):
#            if line[-1:] == '_':
#                line=line[:-1]

        # Whatever is left is the contents of the line. Append everything found so far to temporaryList.
        temporaryList.append( [ line, speaker, currentLineNumber, codeForMetadata ] )

    # Create a chocolate.Strawberry().
    mySpreadsheet=chocolate.Strawberry()

    # Very important: Create the correct header.
    mySpreadsheet.appendRow( ['rawText', 'speaker','metadata' ] )

    # Add data entries and format metadata column appropriately.
    for entry in temporaryList:
        mySpreadsheet.appendRow( [ entry[0], entry[1], str( entry[2] ) + metadataDelimiter + entry[3] ])

    if debug == True:
        mySpreadsheet.printAllTheThings()

    return mySpreadsheet


# This function takes mySpreadsheet as a chocolate.Strawberry() and inserts the contents back to fileNameWithPath.
def output( fileNameWithPath, mySpreadsheet, characterDictionary=None, settings={} ):

    assert isinstance(mySpreadsheet, chocolate.Strawberry)

    # Unpack some variables.
    if 'fileEncoding' in settings:
        fileEncoding=settings['fileEncoding']
    else:
        fileEncoding=defaultTextEncoding

    if 'parseSettingsDictionary' in settings:
        parseSettingsDictionary=settings['parseSettingsDictionary']
    else:
        parseSettingsDictionary=None

    #outputColumn=None
    if ( not 'outputColumn' in settings ):
        #outputColumn=defaultOutputColumn
        outputColumn=len( mySpreadsheet.getRow(1) )
    #elif 'outputColumn' in settings:
    else:
        if ( 'outputColumnIsDefault' in settings ):
            if ( settings[ 'outputColumnIsDefault' ] == True ):
                # User did not choose it, so disregard default value.
                settings[ 'outputColumn' ]=None

        if isinstance( settings[ 'outputColumn' ], int ) == True:
            # This sets outputColumn to an integer like 4.
            outputColumn = settings[ 'outputColumn' ]
        elif isinstance( settings[ 'outputColumn' ], str ) == True:
            if len(settings[ 'outputColumn' ]) == 1:
                try:
                    outputColumn = int(settings[ 'outputColumn' ])
                except:
                    # Then assume it is already valid as-is.
                    outputColumn=settings[ 'outputColumn' ]
            else:
                # This sets outputColumn to a string like 'A' based upon the search value in settings['outputColumn']. Or if the search string was not found, then the function returns None.
                outputColumn=mySpreadsheet.searchHeaders( settings[ 'outputColumn' ] )
                if outputColumn == None:
                    #settings[ 'outputColumn' ] = None
                    # Then the string does not appear in the headers, so revert to using the furthest right value.
                    try:
                        outputColumn = int(settings[ 'outputColumn' ])
                    except:
                        outputColumn = len( mySpreadsheet.getRow(1) )
                        print( ('Warning: Could not find column \'' + settings[ 'outputColumn' ] + '\' in spreadsheet. Using furthest right column value \'' + str(outputColumn) + ':'+ str( mySpreadsheet.getColumn(outputColumn)[0] ) + '\'' ).encode(consoleEncoding) )
        # if settings[ 'outputColumn' ] is not an integer or string, then give up and use a default value.
        else:
            #outputColumn=defaultOutputColumn
            outputColumn = len( mySpreadsheet.getRow(1) )

    # Get the untranslated lines, the translated lines, and related metadata.
    #untranslatedLines = mySpreadsheet.getColumn( 'A' )
    #translatedLines = mySpreadsheet.getColumn( outputColumn )
    #speakerList = mySpreadsheet.getColumn( 'B' )
    #metadataColumn = mySpreadsheet.getColumn( 'C' )

    # Remove header.
    # https://www.w3schools.com/python/ref_list_pop.asp
    #untranslatedLines.pop( 0 )
    #translatedLines.pop( 0 )
    #speakerList.pop( 0 )
    #metadataColumn.pop( 0 )

    # The input file is actually a .txt file so read it in and convert it into a list of strings.
    with open( fileNameWithPath, 'rt', encoding=fileEncoding, errors=inputErrorHandling ) as myFileHandle:
        inputFileContents = myFileHandle.read().splitlines()

    # Get the untranslated lines, the translated lines, and related metadata.
    untranslatedLines = mySpreadsheet.getColumn( 'A' )
    translatedLines = mySpreadsheet.getColumn( outputColumn )
    speakerListAfterTranslation = mySpreadsheet.getColumn( 'B' )
    metadataColumnNew = mySpreadsheet.getColumn( 'C' )

    # Spreadsheets start with row 1 but row 1 contains headers. Therefore, row 2 is the first row with valid data. However, the 'correct' row number has all the data put into a series lists for processing. Lists begin their indexes at 0, so decrement 1 in order to get the correct 2nd item in the spreadsheet.
    currentRow=2 - 1
    nextTranslatedLine=None
    #metadataFromSpreadsheet=None
    #hasEmptyLineAtTheStartOfTheSecondPart=False

    for currentLineNumber,currentLine in enumerate(inputFileContents):
        if nextTranslatedLine == None:
            if currentRow >= len(untranslatedLines):
                break
            nextTranslatedLine=metadataColumnNew[currentRow].partition(metadataDelimiter)[0]
            metadataFromSpreadsheet=metadataColumnNew[currentRow].partition(metadataDelimiter)[2]
            #currentSpeakerForLineFromFile=None
            #hasEmptyLineAtTheStartOfTheSecondPart=False

        # Keep going until the next line that has a translation in the spreadsheet.
        # There is a bug here where nextTranslatedLine is based around currentRow which mean
        if currentLineNumber < int(nextTranslatedLine):
            continue

        # Do a sanity check on the metadata now.
        # There is always an address/code in between two ◆. Store it as metadata for the current line.
        metadataFromFile = currentLine[ 1: currentLine.rfind( '◆' ) ]
        try:
            assert( metadataFromFile == metadataFromSpreadsheet )
        except:
            print( 'nextTranslatedLine=', nextTranslatedLine)
            print( 'currentLine=', currentLine)
            print( 'currentLineNumber=', currentLineNumber)
            print( 'metadataFromFile=', metadataFromFile )
            print( 'metadataFromSpreadsheet=', metadataFromSpreadsheet)
            raise

        # The code has been processed, so get the rest of the line now.
        secondPartOfLineRaw=currentLine[1:].partition('◆')[2]

        # This might be a mistake. If there is a \n in the line, odds are that before it is the speaker name, but a \n at the start might mean a deliberately empty speaker name. A second \n means a line break in the dialogue script (untested). Therefore, it might be required that every dialogue line have a \n. Are there any counter examples? # Update: That is exactly what it means, probably. No counter examples were located.
        secondPartOfLine=None
        # if the line starts with \n then save that information, and then continue processing the string.
        if secondPartOfLineRaw[ :2 ] == r'\n':
            currentSpeakerForLineFromFile=None
            secondPartOfLine=secondPartOfLineRaw[ 2: ]
        else:
            #secondPartOfLine=secondPartOfLineRaw
            # if the line has a new line character, right next to an "「" or similar limited characters, then the part before that might be the speaker's name. syntax example: "\n「" Do not strip whitespace.
            if secondPartOfLineRaw.find(r'\n') == -1:
                print( 'Unspecified error parsing data.' )
                sys.exit( 1 )
            else:
                index=secondPartOfLineRaw.find(r'\n')
                # if the first character after \n is '「'
                #if secondPartOfLineRaw[index+2:index+3] in speakerNameDelimiterList:
                currentSpeakerForLineFromFile=secondPartOfLineRaw.partition( r'\n' )[0]
                #speakerDelimiter=r'\n'
                secondPartOfLine=secondPartOfLineRaw.partition( r'\n' )[2]

        # Sanity check that the line has the untranslated contents.
        assert( secondPartOfLine.find( untranslatedLines[currentRow] ) != -1 )

        # Sanity check the speaker name, if any. The only way to do this is to use the characterDictionary for the mapping of untranslated to translated names.
        if currentSpeakerForLineFromFile != None:
            # then assert that the speaker from the spreadsheet is not None.
            assert( speakerListAfterTranslation[currentRow] != None )
            if isinstance( characterDictionary, dict) == True:
                if speakerListAfterTranslation[currentRow].strip() in characterDictionary.values():
                    untranslatedSpeakerName=None
                    for key,value in characterDictionary.items():
                        # Retrieve the speaker name from the current row in the spreadsheet and reverse translate it back to the untranslated name
                        if speakerListAfterTranslation[currentRow].strip() == value:
                            untranslatedSpeakerName=key
                            break
                    # assert the un-translated name from speakerListAfterTranslation[currentRow] is the same as the currentSpeaker for the current line from the input file in order to validate the translated speaker entry: speakerListAfterTranslation[currentRow] 
                    # assert ( currentSpeakerForLineFromFile.find( untranslatedSpeakerName )  != -1 ) # Which of these are better logic?
                    #assert( untranslatedSpeakerName == currentSpeakerForLineFromFile.strip() ) # The intent is more clear here.
                    try:
                        assert( untranslatedSpeakerName == currentSpeakerForLineFromFile.strip() ) # The intent is more clear here.
                    except:
                        #Sometimes, a certain name or phrase will be translated from the source language into the target language as a duplicate. Like 少年 and 男の子 both getting translated to "Boy". When sanity checking that, the source will not match since 男の子 will be checked against 少年. When that happens, if the first entry in the character dictionary failed, then try to validate that by using the last name that appears in the dictionary. Lazy, but should work as long as there is no more than one duplicate entry. The proper way is to check if any entry matches, which is more complicated than copy/pasting existing code.
                        try:
                            for key,value in characterDictionary.items():
                                # Retrieve the speaker name from the current row in the spreadsheet and reverse translate it back to the untranslated name
                                if speakerListAfterTranslation[currentRow].strip() == value:
                                    untranslatedSpeakerName=key
                            assert( untranslatedSpeakerName == currentSpeakerForLineFromFile.strip() ) # The intent is more clear here.
                        except:
                            # if that still does not work, then print debug information and quit.
                            print( 'nextTranslatedLine=', nextTranslatedLine)
                            print( 'currentLine=', currentLine)
                            print( 'currentLineNumber=', currentLineNumber)
                            print( 'metadataFromFile=', metadataFromFile )
                            print( 'metadataFromSpreadsheet=', metadataFromSpreadsheet)
                            print( 'untranslatedSpeakerName=', untranslatedSpeakerName)
                            print( 'currentSpeakerForLineFromFile.strip()=', currentSpeakerForLineFromFile.strip())
                            raise
                #elif currentSpeakerForLineFromFile not in characterDictionary.values():
                else:
                    print( ( 'Warning: The character dictionary does not have the name \''+ speakerListAfterTranslation[currentRow] + '\' at row number '+ str(currentRow+1) + '.' ).encode(consoleEncoding) )
        #elif currentSpeakerForLineFromFile == None:
#        else:
            # Change from None to empty string to simplify the replacement logic later. #Incorrect. The name needs to come from speakerListAfterTranslation[currentRow]
            #currentSpeakerForLineFromFile=''

        # Fix a few more one off things in the post-translated data. Sort of like post-processing? Word wrap, if any, should be done here. For this engine, word wrap should remove any r'\n', '\n' characters and insert r'\n'
        # This replaces all non-valid cp932 characters with empty strings. There is a warning printed about this if it happens.
        tempTranslatedData = functions.normalizeEncoding( translatedLines[ currentRow ], defaultTargetEncoding )

        # The line number was validated. The metadata was validated. The speaker, if any, was validated. The translated value is in the spreadsheet exists, probably. Now it is time to rebuild the string from scratch and replace the line in the file with this new string.

        # How it gets built differs depending upon if there is a speaker or not. This could be updated to be simpler, but whatever.
        if speakerListAfterTranslation[currentRow] == None:
            newString='◆' + metadataFromFile + '◆' + r'\n' + tempTranslatedData
        else:
            newString='◆' + metadataFromFile + '◆' + speakerListAfterTranslation[ currentRow ] + r'\n' + tempTranslatedData

        # Update the input file and move on to the next entry.
        inputFileContents[currentLineNumber] = newString

        # Clear variables.
        nextTranslatedLine=None
        currentSpeakerForLineFromFile=None

        # Move on to next entry.
        currentRow+=1

    # Once inputFileContents is fully updated, just send it back to the calling function so it can be written out to disk.
    # The code that calls this function will check if the return type is a chocolate.Strawberry(), a string, or a list and handle writing out the file appropriately, so there is no need to do anything more here.
    return inputFileContents

